version: '3.7'
services:
  api-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - seasidefm
    env_file:
      - .env
    ports:
      - "5000:5000"
    entrypoint: ["python", "-m", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "5000"]

networks:
  seasidefm:
    external: true