apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-hdd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  path: "/mnt/plex/storage/kube"
